# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'MyLocationsMVC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyLocationsMVC
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'Alamofire', '~> 5.5'
end
